# Script to define all 50 products and generate data / markup cleanly
import json

PRODUCTS = [
  # --- MANTENIMIENTO Y LIMPIEZA DEL HOGAR (15 productos) ---
  {
    "id": "hidrolavadora-1400w",
    "nombre": "Hidrolavadora Alta Presión 1400W 110 Bar",
    "categoriaId": "mantenimiento-limpieza",
    "categoriaNombre": "Mantenimiento y Limpieza",
    "desc": "Bomba de aluminio de alto rendimiento con manguera de 5m, lanza con boquilla regulable y aplicador de espuma.",
    "precio": 92500,
    "precioFormateado": "$92.500",
    "antes": "$108.900",
    "oferta": "-15%",
    "imagen": "img/productos/hidrolavadora-1400w.jpg",
    "destacado": True,
    "stock": True
  },
  {
    "id": "aspiradora-20l",
    "nombre": "Aspiradora Polvo y Agua 20L 1400W",
    "categoriaId": "mantenimiento-limpieza",
    "categoriaNombre": "Mantenimiento y Limpieza",
    "desc": "Tambor de acero inoxidable, función soplador, filtro lavable HEPA y kit de boquillas para piso y rincones.",
    "precio": 84900,
    "precioFormateado": "$84.900",
    "antes": "$99.000",
    "oferta": "-14%",
    "imagen": "img/productos/aspiradora-20l.jpg",
    "destacado": False,
    "stock": True
  },
  {
    "id": "mopa-giratoria-360",
    "nombre": "Set Mopa Giratoria 360° Acero Inoxidable",
    "categoriaId": "mantenimiento-limpieza",
    "categoriaNombre": "Mantenimiento y Limpieza",
    "desc": "Balde con centrífuga escurridora reforzada de acero y 2 paños de microfibra de alta absorción.",
    "precio": 21400,
    "precioFormateado": "$21.400",
    "antes": "$26.000",
    "oferta": "-18%",
    "imagen": "img/productos/mopa-giratoria-360.jpg",
    "destacado": False,
    "stock": True
  },
  {
    "id": "escalera-aluminio-5",
    "nombre": "Escalera Tijera de Aluminio 5 Escalones",
    "categoriaId": "mantenimiento-limpieza",
    "categoriaNombre": "Mantenimiento y Limpieza",
    "desc": "Perfil reforzado antideslizante con capacidad de carga hasta 150kg. Liviana y plegable.",
    "precio": 48600,
    "precioFormateado": "$48.600",
    "antes": "$56.000",
    "oferta": "Oferta",
    "imagen": "img/productos/escalera-aluminio-5.jpg",
    "destacado": False,
    "stock": True
  },
  {
    "id": "cinta-teflon-3-4",
    "nombre": "Cinta de Teflón Alta Densidad 3/4\" x 20m",
    "categoriaId": "mantenimiento-limpieza",
    "categoriaNombre": "Mantenimiento y Limpieza",
    "desc": "Cinta selladora de PTFE para roscas y caños de agua y gas. Sella sin endurecer y previene fugas.",
    "precio": 2400,
    "precioFormateado": "$2.400",
    "antes": "$3.100",
    "oferta": "-22%",
    "imagen": "img/productos/cinta-teflon-3-4.jpg",
    "destacado": False,
    "stock": True
  },
  {
    "id": "flexible-mallado-1-2",
    "nombre": "Flexible Mallado Acero Inoxidable 1/2\" x 40cm",
    "categoriaId": "mantenimiento-limpieza",
    "categoriaNombre": "Mantenimiento y Limpieza",
    "desc": "Conexión flexible macho-hembra para grifería, bidet y termotanques. Malla de acero quirúrgico AISI 304.",
    "precio": 6800,
    "precioFormateado": "$6.800",
    "antes": "$8.500",
    "oferta": "-20%",
    "imagen": "img/productos/flexible-mallado-1-2.jpg",
    "destacado": False,
    "stock": True
  },
  {
    "id": "canilla-esferica-1-2",
    "nombre": "Canilla Esférica para Jardín Metálica 1/2\"",
    "categoriaId": "mantenimiento-limpieza",
    "categoriaNombre": "Mantenimiento y Limpieza",
    "desc": "Paso total con palanca ergonómica roja y pico para acople rápido de manguera de riego.",
    "precio": 9900,
    "precioFormateado": "$9.900",
    "antes": "$12.500",
    "oferta": "-20%",
    "imagen": "img/productos/canilla-esferica-1-2.jpg",
    "destacado": False,
    "stock": True
  },
  {
    "id": "adhesivo-pvc-250",
    "nombre": "Adhesivo para Caños de PVC Rígido 250cc",
    "categoriaId": "mantenimiento-limpieza",
    "categoriaNombre": "Mantenimiento y Limpieza",
    "desc": "Pegamento para cañerías cloacales y pluviales con pincel aplicador integrado. Secado ultra rápido.",
    "precio": 7400,
    "precioFormateado": "$7.400",
    "antes": "$9.200",
    "oferta": "-19%",
    "imagen": "img/productos/adhesivo-pvc-250.jpg",
    "destacado": False,
    "stock": True
  },
  {
    "id": "tubo-termofusion-20mm",
    "nombre": "Tubo Termofusión Verde 20mm x 4m PN20",
    "categoriaId": "mantenimiento-limpieza",
    "categoriaNombre": "Mantenimiento y Limpieza",
    "desc": "Caño tricapa para agua fría y caliente de alta presión. Máxima resistencia a la temperatura y atóxico.",
    "precio": 11500,
    "precioFormateado": "$11.500",
    "antes": "$14.200",
    "oferta": "-19%",
    "imagen": "img/productos/tubo-termofusion-20mm.jpg",
    "destacado": False,
    "stock": True
  },
  {
    "id": "silicona-neutra-transparente",
    "nombre": "Silicona Neutra Transparente 280ml",
    "categoriaId": "mantenimiento-limpieza",
    "categoriaNombre": "Mantenimiento y Limpieza",
    "desc": "Sellador multiuso para baños, cocinas, aberturas y vidrio. Antihongos y resistente a la intemperie.",
    "precio": 8200,
    "precioFormateado": "$8.200",
    "antes": "$10.400",
    "oferta": "-21%",
    "imagen": "img/productos/silicona-neutra-transparente.jpg",
    "destacado": False,
    "stock": True
  },
  {
    "id": "espuma-poliuretano-500ml",
    "nombre": "Espuma de Poliuretano Expansiva 500ml",
    "categoriaId": "mantenimiento-limpieza",
    "categoriaNombre": "Mantenimiento y Limpieza",
    "desc": "Aislante térmico y acústico para fijación de marcos de puertas, ventanas y relleno de huecos.",
    "precio": 12800,
    "precioFormateado": "$12.800",
    "antes": "$15.900",
    "oferta": "-19%",
    "imagen": "img/productos/espuma-poliuretano-500ml.jpg",
    "destacado": False,
    "stock": True
  },
  {
    "id": "cinta-papel-enmascarar",
    "nombre": "Cinta de Papel para Pintor 24mm x 50m",
    "categoriaId": "mantenimiento-limpieza",
    "categoriaNombre": "Mantenimiento y Limpieza",
    "desc": "Cinta de enmascarar masking tape de fácil desprendimiento sin dejar residuos adhesivos.",
    "precio": 3100,
    "precioFormateado": "$3.100",
    "antes": "$4.000",
    "oferta": "-22%",
    "imagen": "img/productos/cinta-papel-enmascarar.jpg",
    "destacado": False,
    "stock": True
  },
  {
    "id": "adhesivo-montaje-pulpito",
    "nombre": "Adhesivo de Montaje Agarre Inmediato 250g",
    "categoriaId": "mantenimiento-limpieza",
    "categoriaNombre": "Mantenimiento y Limpieza",
    "desc": "Reemplaza clavos y tornillos. Gran agarre inicial para zócalos, madera, metal y cerámicos.",
    "precio": 7900,
    "precioFormateado": "$7.900",
    "antes": "$9.800",
    "oferta": "-19%",
    "imagen": "img/productos/adhesivo-montaje-pulpito.jpg",
    "destacado": False,
    "stock": True
  },
  {
    "id": "sellador-acrilico-grietas",
    "nombre": "Sellador Acrílico Pintable para Grietas 280ml",
    "categoriaId": "mantenimiento-limpieza",
    "categoriaNombre": "Mantenimiento y Limpieza",
    "desc": "Sellador elástico blanco para fisuras en paredes de yeso y mampostería. Fácil de lijar y pintar.",
    "precio": 5900,
    "precioFormateado": "$5.900",
    "antes": "$7.500",
    "oferta": "-21%",
    "imagen": "img/productos/sellador-acrilico-grietas.jpg",
    "destacado": False,
    "stock": True
  },
  {
    "id": "balde-albanil-reforzado",
    "nombre": "Balde de Albañil Plástico Reforzado 10L",
    "categoriaId": "mantenimiento-limpieza",
    "categoriaNombre": "Mantenimiento y Limpieza",
    "desc": "Balde de obra con manija metálica resistente y graduación interna. Ideal mezclas y limpieza pesada.",
    "precio": 3600,
    "precioFormateado": "$3.600",
    "antes": "$4.800",
    "oferta": "-25%",
    "imagen": "img/productos/balde-albanil-reforzado.jpg",
    "destacado": False,
    "stock": True
  },

  # --- ELECTRICIDAD (8 productos) ---
  {
    "id": "rollo-cable-2-5",
    "nombre": "Rollo Cable Unipolar 2.5mm IRAM 100m",
    "categoriaId": "electricidad",
    "categoriaNombre": "Electricidad",
    "desc": "Cobre puro 100% antihidrocarburo y no propagante de llama. Aprobado según normativa IRAM.",
    "precio": 38500,
    "precioFormateado": "$38.500",
    "antes": "$45.000",
    "oferta": "-15%",
    "imagen": "img/productos/rollo-cable-2-5.jpg",
    "destacado": True,
    "stock": True
  },
  {
    "id": "tablero-termicas",
    "nombre": "Kit Tablero Térmicas y Disyuntor Bipolar",
    "categoriaId": "electricidad",
    "categoriaNombre": "Electricidad",
    "desc": "Caja estanca para 8 bocas + Disyuntor bipolar 25A + 2 Térmicas 16A y 20A normalizadas Sica.",
    "precio": 45200,
    "precioFormateado": "$45.200",
    "antes": "$52.000",
    "oferta": "Pack",
    "imagen": "img/productos/tablero-termicas.jpg",
    "destacado": False,
    "stock": True
  },
  {
    "id": "tester-multimetro",
    "nombre": "Multímetro Tester Digital Profesional",
    "categoriaId": "electricidad",
    "categoriaNombre": "Electricidad",
    "desc": "Medición precisa de voltaje AC/DC, amperaje, resistencia y continuidad sonora. Puntas y batería incluidas.",
    "precio": 16800,
    "precioFormateado": "$16.800",
    "antes": "$21.000",
    "oferta": "-20%",
    "imagen": "img/productos/tester-multimetro.jpg",
    "destacado": False,
    "stock": True
  },
  {
    "id": "reflector-led-50w",
    "nombre": "Reflector Proyector LED 50W Exterior IP65",
    "categoriaId": "electricidad",
    "categoriaNombre": "Electricidad",
    "desc": "Luz blanca fría de alta potencia 4500 lúmenes, resistente a lluvia y polvo para frentes o talleres.",
    "precio": 19500,
    "precioFormateado": "$19.500",
    "antes": "$24.000",
    "oferta": "Destacado",
    "imagen": "img/productos/reflector-led-50w.jpg",
    "destacado": False,
    "stock": True
  },
  {
    "id": "cinta-aisladora-tacsa",
    "nombre": "Cinta Aisladora PVC Ignífuga 20m Tacsa",
    "categoriaId": "electricidad",
    "categoriaNombre": "Electricidad",
    "desc": "Cinta aislante profesional de PVC de 20 metros. Aislación eléctrica certificada hasta 600V.",
    "precio": 2800,
    "precioFormateado": "$2.800",
    "antes": "$3.600",
    "oferta": "-22%",
    "imagen": "img/productos/cinta-aisladora-tacsa.jpg",
    "destacado": False,
    "stock": True
  },
  {
    "id": "pack-led-9w-x10",
    "nombre": "Pack x10 Lámparas LED 9W E27 Luz Fría",
    "categoriaId": "electricidad",
    "categoriaNombre": "Electricidad",
    "desc": "Pack ahorro de 10 focos LED rosca estándar E27 de bajo consumo A+. Equivalente a 75W incandescente.",
    "precio": 16500,
    "precioFormateado": "$16.500",
    "antes": "$21.000",
    "oferta": "-21%",
    "imagen": "img/productos/pack-led-9w-x10.jpg",
    "destacado": False,
    "stock": True
  },
  {
    "id": "punto-toma-armado",
    "nombre": "Punto y Toma Corriente Armado con Placa",
    "categoriaId": "electricidad",
    "categoriaNombre": "Electricidad",
    "desc": "Módulo armado blanco con llave interruptora y tomacorriente de 10A con placa y bastidor.",
    "precio": 4900,
    "precioFormateado": "$4.900",
    "antes": "$6.200",
    "oferta": "-21%",
    "imagen": "img/productos/punto-toma-armado.jpg",
    "destacado": False,
    "stock": True
  },
  {
    "id": "cano-corrugado-3-4",
    "nombre": "Caño Corrugado Blanco Ignífugo 3/4\" x 25m",
    "categoriaId": "electricidad",
    "categoriaNombre": "Electricidad",
    "desc": "Rollo de caño corrugado normalizado para embutir en pared o losa. Autoextinguible y flexible.",
    "precio": 14200,
    "precioFormateado": "$14.200",
    "antes": "$17.800",
    "oferta": "-20%",
    "imagen": "img/productos/cano-corrugado-3-4.jpg",
    "destacado": False,
    "stock": True
  },

  # --- LIBROS / E-BOOK (4 productos) ---
  {
    "id": "ebook-electricidad",
    "nombre": "E-Book: Manual de Instalaciones Eléctricas",
    "categoriaId": "libros-ebook",
    "categoriaNombre": "Libros / E-Book",
    "desc": "Guía completa digital con diagramas de circuitos, cálculo de conductores y normativas de seguridad AEA.",
    "precio": 6900,
    "precioFormateado": "$6.900",
    "antes": "$9.500",
    "oferta": "-27%",
    "imagen": "img/productos/ebook-electricidad.jpg",
    "destacado": False,
    "stock": True
  },
  {
    "id": "ebook-plomeria",
    "nombre": "E-Book: Guía Práctica de Plomería y Gas",
    "categoriaId": "libros-ebook",
    "categoriaNombre": "Libros / E-Book",
    "desc": "Técnicas de termofusión, desagües cloacales, bombas de agua y resolución de pérdidas comunes.",
    "precio": 5800,
    "precioFormateado": "$5.800",
    "antes": "$8.000",
    "oferta": "-27%",
    "imagen": "img/productos/ebook-plomeria.jpg",
    "destacado": False,
    "stock": True
  },
  {
    "id": "ebook-herreria",
    "nombre": "E-Book: Técnicas de Soldadura y Herrería",
    "categoriaId": "libros-ebook",
    "categoriaNombre": "Libros / E-Book",
    "desc": "Soldadura con electrodo revestido y MIG/MAG, escuadras, cortes de perfiles y proyectos paso a paso.",
    "precio": 7500,
    "precioFormateado": "$7.500",
    "antes": "$10.000",
    "oferta": "-25%",
    "imagen": "img/productos/ebook-herreria.jpg",
    "destacado": False,
    "stock": True
  },
  {
    "id": "ebook-durlock",
    "nombre": "E-Book: Guía de Construcción en Seco",
    "categoriaId": "libros-ebook",
    "categoriaNombre": "Libros / E-Book",
    "desc": "Manual paso a paso para tabiques, cielorrasos suspendidos, masillado y cálculo de perfilería.",
    "precio": 8200,
    "precioFormateado": "$8.200",
    "antes": "$11.000",
    "oferta": "-25%",
    "imagen": "img/productos/ebook-durlock.jpg",
    "destacado": False,
    "stock": True
  },

  # --- HERRAMIENTA SEGURIDAD (19 productos) ---
  {
    "id": "taladro-650w",
    "nombre": "Taladro Percutor 650W + Maletín",
    "categoriaId": "herramienta-seguridad",
    "categoriaNombre": "Herramienta Seguridad",
    "desc": "Mandril de 13mm, velocidad variable y reversible. Potente motor con selector de percusión y accesorios.",
    "precio": 64900,
    "precioFormateado": "$64.900",
    "antes": "$81.100",
    "oferta": "-20%",
    "imagen": "img/productos/taladro-650w.jpg",
    "destacado": True,
    "stock": True
  },
  {
    "id": "amoladora-4-1-2",
    "nombre": "Amoladora Angular 4 1/2\" 850W",
    "categoriaId": "herramienta-seguridad",
    "categoriaNombre": "Herramienta Seguridad",
    "desc": "Diseño ergonómico, traba de eje y guarda de protección ajustable contra chispas. 11000 RPM.",
    "precio": 58900,
    "precioFormateado": "$58.900",
    "antes": "$69.000",
    "oferta": "Oferta",
    "imagen": "img/productos/amoladora-4-1-2.jpg",
    "destacado": True,
    "stock": True
  },
  {
    "id": "casco-seguridad",
    "nombre": "Casco de Seguridad Industrial Homologado",
    "categoriaId": "herramienta-seguridad",
    "categoriaNombre": "Herramienta Seguridad",
    "desc": "Casco de polietileno de alta densidad con arnés a cremallera regulable y banda antisudor.",
    "precio": 8500,
    "precioFormateado": "$8.500",
    "antes": "$11.000",
    "oferta": "-22%",
    "imagen": "img/productos/casco-seguridad.jpg",
    "destacado": False,
    "stock": True
  },
  {
    "id": "antiparras-seguridad",
    "nombre": "Antiparras de Seguridad Anti-Empaño UV400",
    "categoriaId": "herramienta-seguridad",
    "categoriaNombre": "Herramienta Seguridad",
    "desc": "Visor envolvente de policarbonato con patillas ajustables y máxima resistencia a impactos.",
    "precio": 4200,
    "precioFormateado": "$4.200",
    "antes": "$5.500",
    "oferta": "-23%",
    "imagen": "img/productos/antiparras-seguridad.jpg",
    "destacado": False,
    "stock": True
  },
  {
    "id": "arnes-seguridad",
    "nombre": "Arnés de Seguridad Integral Anticaídas",
    "categoriaId": "herramienta-seguridad",
    "categoriaNombre": "Herramienta Seguridad",
    "desc": "Con toma dorsal y frontal para trabajos en altura. Cintas de poliéster de alta tenacidad homologadas.",
    "precio": 34500,
    "precioFormateado": "$34.500",
    "antes": "$42.000",
    "oferta": "Seguridad",
    "imagen": "img/productos/arnes-seguridad.jpg",
    "destacado": False,
    "stock": True
  },
  {
    "id": "martillo-galponero",
    "nombre": "Martillo Galponero Cabo Fibra de Vidrio",
    "categoriaId": "herramienta-seguridad",
    "categoriaNombre": "Herramienta Seguridad",
    "desc": "Cabeza forjada de acero al carbono con uña curva sacaclavos y mango ergonómico antideslizante.",
    "precio": 18900,
    "precioFormateado": "$18.900",
    "antes": "$23.500",
    "oferta": "-20%",
    "imagen": "img/productos/martillo-galponero.jpg",
    "destacado": False,
    "stock": True
  },
  {
    "id": "pinza-universal-8",
    "nombre": "Pinza Universal 8 Pulgadas Aislada 1000V",
    "categoriaId": "herramienta-seguridad",
    "categoriaNombre": "Herramienta Seguridad",
    "desc": "Pinza de fuerza forjada en acero cromo vanadio con mangos bimateriales de alta aislación.",
    "precio": 15400,
    "precioFormateado": "$15.400",
    "antes": "$19.200",
    "oferta": "-20%",
    "imagen": "img/productos/pinza-universal-8.jpg",
    "destacado": False,
    "stock": True
  },
  {
    "id": "llave-francesa-10",
    "nombre": "Llave Francesa Ajustable 10\" Cromada",
    "categoriaId": "herramienta-seguridad",
    "categoriaNombre": "Herramienta Seguridad",
    "desc": "Apertura amplia con escala milimétrica grabada con láser y mecanismo de ajuste suave y preciso.",
    "precio": 17800,
    "precioFormateado": "$17.800",
    "antes": "$22.000",
    "oferta": "-19%",
    "imagen": "img/productos/llave-francesa-10.jpg",
    "destacado": False,
    "stock": True
  },
  {
    "id": "cinta-metrica-5m",
    "nombre": "Cinta Métrica Flexómetro 5m con Freno",
    "categoriaId": "herramienta-seguridad",
    "categoriaNombre": "Herramienta Seguridad",
    "desc": "Cinta metálica de 19mm con recubrimiento mate antirreflejo, botón de traba y clip para cinturón.",
    "precio": 6500,
    "precioFormateado": "$6.500",
    "antes": "$8.200",
    "oferta": "-20%",
    "imagen": "img/productos/cinta-metrica-5m.jpg",
    "destacado": False,
    "stock": True
  },
  {
    "id": "nivel-aluminio-40cm",
    "nombre": "Nivel Tubular de Aluminio Magnético 40cm",
    "categoriaId": "herramienta-seguridad",
    "categoriaNombre": "Herramienta Seguridad",
    "desc": "Cuerpo de aluminio reforzado con base magnética y 3 burbujas de precisión (45°, 90° y 180°).",
    "precio": 13900,
    "precioFormateado": "$13.900",
    "antes": "$17.500",
    "oferta": "-20%",
    "imagen": "img/productos/nivel-aluminio-40cm.jpg",
    "destacado": False,
    "stock": True
  },
  {
    "id": "juego-destornilladores-x6",
    "nombre": "Set x6 Destornilladores Planos y Phillips",
    "categoriaId": "herramienta-seguridad",
    "categoriaNombre": "Herramienta Seguridad",
    "desc": "Puntas imantadas templadas de acero Cr-V. Incluye 3 planos y 3 phillips con mango bimaterial.",
    "precio": 16200,
    "precioFormateado": "$16.200",
    "antes": "$20.500",
    "oferta": "-21%",
    "imagen": "img/productos/juego-destornilladores-x6.jpg",
    "destacado": False,
    "stock": True
  },
  {
    "id": "arco-sierra-metales",
    "nombre": "Arco de Sierra para Metales 12\" con Hoja",
    "categoriaId": "herramienta-seguridad",
    "categoriaNombre": "Herramienta Seguridad",
    "desc": "Estructura tubular robusta con tuerca mariposa de tensión y hoja bimetálica flexible de 24 dpp.",
    "precio": 12400,
    "precioFormateado": "$12.400",
    "antes": "$15.500",
    "oferta": "-20%",
    "imagen": "img/productos/arco-sierra-metales.jpg",
    "destacado": False,
    "stock": True
  },
  {
    "id": "tarugos-nylon-8",
    "nombre": "Tarugos de Nylon Nº 8 con Tope y Tornillos x100",
    "categoriaId": "herramienta-seguridad",
    "categoriaNombre": "Herramienta Seguridad",
    "desc": "Bolsa de 100 tarugos plásticos fijadores con tope para ladrillo común y hueco, con tornillos fix.",
    "precio": 5800,
    "precioFormateado": "$5.800",
    "antes": "$7.500",
    "oferta": "-23%",
    "imagen": "img/productos/tarugos-nylon-8.jpg",
    "destacado": False,
    "stock": True
  },
  {
    "id": "tornillos-drywall-t2",
    "nombre": "Tornillos Drywall T2 Aguja para Durlock x100",
    "categoriaId": "herramienta-seguridad",
    "categoriaNombre": "Herramienta Seguridad",
    "desc": "Tornillos fosfatizados negros 6x1 1/4\" punta aguja especiales para fijación de placas de yeso.",
    "precio": 4300,
    "precioFormateado": "$4.300",
    "antes": "$5.600",
    "oferta": "-23%",
    "imagen": "img/productos/tornillos-drywall-t2.jpg",
    "destacado": False,
    "stock": True
  },
  {
    "id": "tornillos-t1-aguja",
    "nombre": "Tornillos T1 Punta Aguja 8x9/16\" x100",
    "categoriaId": "herramienta-seguridad",
    "categoriaNombre": "Herramienta Seguridad",
    "desc": "Tornillos autoperforantes cabeza lenteja punta aguja para unión de perfiles de chapa y durlock.",
    "precio": 3900,
    "precioFormateado": "$3.900",
    "antes": "$5.000",
    "oferta": "-22%",
    "imagen": "img/productos/tornillos-t1-aguja.jpg",
    "destacado": False,
    "stock": True
  },
  {
    "id": "clavos-punta-paris",
    "nombre": "Clavos Punta París 2 1/2 Pulgadas x 1 Kg",
    "categoriaId": "herramienta-seguridad",
    "categoriaNombre": "Herramienta Seguridad",
    "desc": "Clavos de acero pulido de primera calidad para carpintería, encofrados y madera general.",
    "precio": 4700,
    "precioFormateado": "$4.700",
    "antes": "$6.000",
    "oferta": "-22%",
    "imagen": "img/productos/clavos-punta-paris.jpg",
    "destacado": False,
    "stock": True
  },
  {
    "id": "remaches-aluminio-ciegos",
    "nombre": "Remaches Rápidos de Aluminio 4x12mm x100",
    "categoriaId": "herramienta-seguridad",
    "categoriaNombre": "Herramienta Seguridad",
    "desc": "Remaches ciegos de cuerpo de aluminio y vástago de acero para uniones metálicas duraderas.",
    "precio": 3800,
    "precioFormateado": "$3.800",
    "antes": "$4.900",
    "oferta": "-22%",
    "imagen": "img/productos/remaches-aluminio-ciegos.jpg",
    "destacado": False,
    "stock": True
  },
  {
    "id": "cuchara-albanil-7",
    "nombre": "Cuchara de Albañil Forjada Nº 7 Cabo Madera",
    "categoriaId": "herramienta-seguridad",
    "categoriaNombre": "Herramienta Seguridad",
    "desc": "Hoja forjada de una sola pieza en acero especial, templada y rectificada con cabo de madera lustrado.",
    "precio": 14500,
    "precioFormateado": "$14.500",
    "antes": "$18.200",
    "oferta": "-20%",
    "imagen": "img/productos/cuchara-albanil-7.jpg",
    "destacado": False,
    "stock": True
  },
  {
    "id": "disco-diamantado-115",
    "nombre": "Disco Diamantado Continuo 115mm Cerámicos",
    "categoriaId": "herramienta-seguridad",
    "categoriaNombre": "Herramienta Seguridad",
    "desc": "Corte fino y prolijo sin desportillar en cerámicas, azulejos y porcelanatos para amoladora 4 1/2\".",
    "precio": 9200,
    "precioFormateado": "$9.200",
    "antes": "$11.800",
    "oferta": "-22%",
    "imagen": "img/productos/disco-diamantado-115.jpg",
    "destacado": False,
    "stock": True
  },

  # --- MAYORISTA COMBOS (4 productos) ---
  {
    "id": "combo-duo-power",
    "nombre": "Combo Dúo Power: Taladro + Amoladora",
    "categoriaId": "mayorista-combos",
    "categoriaNombre": "Mayorista Combos",
    "desc": "Kit profesional completo: Taladro percutor 650W + Amoladora 850W con maletín y 10 discos de regalo.",
    "precio": 109900,
    "precioFormateado": "$109.900",
    "antes": "$135.000",
    "oferta": "-19%",
    "imagen": "img/productos/combo-duo-power.jpg",
    "destacado": True,
    "stock": True
  },
  {
    "id": "combo-albanileria",
    "nombre": "Combo Obra: Carretilla + Cuchara + Nivel + 3 Baldes",
    "categoriaId": "mayorista-combos",
    "categoriaNombre": "Mayorista Combos",
    "desc": "Kit mayorista para construcción: Carretilla chapa reforzada 80L + cuchara forjada + nivel + baldes.",
    "precio": 78000,
    "precioFormateado": "$78.000",
    "antes": "$94.000",
    "oferta": "Pack Obra",
    "imagen": "img/productos/combo-albanileria.jpg",
    "destacado": False,
    "stock": True
  },
  {
    "id": "pack-discos-corte",
    "nombre": "Pack Mayorista Discos de Corte 115mm x 50u",
    "categoriaId": "mayorista-combos",
    "categoriaNombre": "Mayorista Combos",
    "desc": "Caja cerrada de 50 discos de corte ultrafinos 1mm para amoladora angular de 4 1/2\". Máxima durabilidad.",
    "precio": 32000,
    "precioFormateado": "$32.000",
    "antes": "$41.000",
    "oferta": "Mayorista",
    "imagen": "img/productos/pack-discos-corte.jpg",
    "destacado": False,
    "stock": True
  },
  {
    "id": "combo-electricista",
    "nombre": "Combo Electricista Pro: Pasacable + Pinza + Pelacables",
    "categoriaId": "mayorista-combos",
    "categoriaNombre": "Mayorista Combos",
    "desc": "Cinta pasacable de acero 20m + Pinza universal aislada 1000V + Pelacables automático + Buscapolo digital.",
    "precio": 49900,
    "precioFormateado": "$49.900",
    "antes": "$62.000",
    "oferta": "-20%",
    "imagen": "img/productos/combo-electricista.jpg",
    "destacado": False,
    "stock": True
  }
]

print(f"Total productos definidos: {len(PRODUCTS)}")
by_cat = {}
for p in PRODUCTS:
    by_cat[p['categoriaId']] = by_cat.get(p['categoriaId'], 0) + 1
print("Por categoría:", by_cat)
